/**
 * @fileoverview gRPC-Web generated client stub for userquerysession
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.2
// source: userquerysession.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.userquerysession = require('./userquerysession_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.userquerysession.UserQueryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.userquerysession.UserQueryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.userquerysession.UserQuery,
 *   !proto.userquerysession.UserID>}
 */
const methodDescriptor_UserQueryService_StartSession = new grpc.web.MethodDescriptor(
  '/userquerysession.UserQueryService/StartSession',
  grpc.web.MethodType.UNARY,
  proto.userquerysession.UserQuery,
  proto.userquerysession.UserID,
  /**
   * @param {!proto.userquerysession.UserQuery} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.userquerysession.UserID.deserializeBinary
);


/**
 * @param {!proto.userquerysession.UserQuery} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.userquerysession.UserID)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.userquerysession.UserID>|undefined}
 *     The XHR Node Readable Stream
 */
proto.userquerysession.UserQueryServiceClient.prototype.startSession =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/userquerysession.UserQueryService/StartSession',
      request,
      metadata || {},
      methodDescriptor_UserQueryService_StartSession,
      callback);
};


/**
 * @param {!proto.userquerysession.UserQuery} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.userquerysession.UserID>}
 *     Promise that resolves to the response
 */
proto.userquerysession.UserQueryServicePromiseClient.prototype.startSession =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/userquerysession.UserQueryService/StartSession',
      request,
      metadata || {},
      methodDescriptor_UserQueryService_StartSession);
};


module.exports = proto.userquerysession;

