# Use the base Envoy image for your platform
FROM --platform=linux/amd64 envoyproxy/envoy:v1.28.0

# Copy the necessary files into the container
COPY set_namespace.sh /tmp/set_namespace.sh
COPY envoy.yaml /etc/envoy.yaml

# Set the NAMESPACE environment variable from the build-time ARG
ARG NAMESPACE
ENV NAMESPACE=${NAMESPACE}

# Make the shell script executable and execute it to replace the namespace in envoy.yaml
RUN chmod +x /tmp/set_namespace.sh && /bin/sh -c '/tmp/set_namespace.sh $NAMESPACE /etc/envoy.yaml'

# Expose the necessary ports
EXPOSE 1337
EXPOSE 8888


CMD /usr/local/bin/envoy -c /etc/envoy.yaml -l debug --service-cluster proxy
