apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 2 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: anakin1612/grpc-server:vDefault # v4.0 is the aws image, last stable version: {e0, prodBeta00=arm)
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: "512Mi" # Request 512 megabytes of memory
            limits:
              memory: "1024Mi" # Limit memory usage to 1024 megabytes
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
