apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  selector:
    app: grpc-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  clusterIP: None

