apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  selector:
    app: envoy
  ports:
    - protocol: TCP
      name: grpc
      port: 1337
      targetPort: 1337
    - protocol: TCP
      name: admin
      port: 8888
      targetPort: 8888
  type: LoadBalancer
