FROM node:14
# Set the working directory in the container

WORKDIR /app
# Copy package.json and package-lock.json to the working directory

COPY package*.json ./
# Install dependencies

RUN npm install
# Copy all files from the current directory to the container

COPY . .
# Expose the port the app runs on

EXPOSE 3000


# Command to run the app
CMD ["node", "./backend/server.js"]
